name: MERN CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Backend Dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run Backend Tests
        run: npm test
        working-directory: ./backend
        env:
          MONGODB_URL: mongodb://localhost:27017
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CLOUDINARY_NAME: "test-cloud-name"
          CLOUDINARY_API_KEY: "test-key"
          CLOUDINARY_SECRET_KEY: "test-secret"

  build-and-test-frontend:
    runs-on: ubuntu-latest
    needs: build-and-test-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: ./frontend

      # Run E2E tests with dev server bound to 127.0.0.1
      - name: Run Frontend E2E Tests
        run: npx start-server-and-test "npm run dev -- --host 127.0.0.1" http://127.0.0.1:5173 "npm run test:e2e"
        working-directory: ./frontend
        env:
          VITE_BACKEND_URL: "http://localhost:4000"
          APP_URL: "http://127.0.0.1:5173"

      - name: Build Frontend for Production
        run: npm run build
        working-directory: ./frontend
